### ISSUE TITLE
逆向分析问题，请问您是否找到了切换视频的方法

### ISSUE THREAD

**Issue by za123** [li-phone/DouyinCrawler#1]
如题。
本来是打算做一个采集用户粉丝的hook操作，但是在切换视频这里卡了很久，无法继续下一步

**Comment by li-phone** [comment]
您好，请问是指apk安装包逆向分析源码这个过程吗？这个抖音app混淆了它的代码，我没看懂app的源码，抱歉啊！┭┮﹏┭┮

**Comment by za123** [comment]
没事没事 ，我在看雪论坛已经发现有同样的帖子了
